version: "3.8"
services:
  backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://postgres:password@database:5432/mydatabase
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
